import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {launchBrowser} from './support/runtime.mjs';
import {selectLocalBook} from './support/library-entry.mjs';
const output=process.env.QA_OUTPUT || '/tmp/asset-library-qa';
const fixture=execFileSync(process.execPath,['--disable-warning=ExperimentalWarning','--experimental-strip-types','--experimental-loader=./tests/node-types-loader.mjs','--input-type=module','-e',`
import {DEFAULT_PROJECT,cloneProject} from './app/story-data.ts';
import {createStoryDocument} from './app/story-project-document.ts';
const p=cloneProject(DEFAULT_PROJECT); p.chapters=p.chapters.slice(0,1);p.lines=p.lines.slice(0,1);
p.chapters[0].leftAssetId='heungbu.character.heungbu-default';p.chapters[0].characterAssetIds=['heungbu.character.heungbu-default'];p.lines[0].leftAssetId='heungbu.character.heungbu-default';p.creativeMemos=[];
console.log(JSON.stringify(createStoryDocument({project:p,savedAt:new Date().toISOString(),appVersion:'test'})));
`],{encoding:'utf8'}).trim();
const browser=await launchBrowser(output);
try {for(const [width,height] of [[1365,900],[390,844]]) {
 const page=await browser.newPage({viewport:{width,height}});
 await page.goto(process.env.QA_URL || 'http://localhost:3010');
 await page.evaluate(doc=>{localStorage.clear();localStorage.setItem('storygame:draft:v1',doc);localStorage.setItem('storygame:active:v1',doc)},fixture);
 await page.reload();await selectLocalBook(page);await page.getByRole('button',{name:'이어만들기',exact:true}).click();
 await page.getByRole('button',{name:'컷 꾸미기',exact:true}).first().click();
 const opener=page.locator('.scene-essential-assets button').first();await opener.click();
 const dialog=page.getByRole('dialog',{name:'왼쪽 표정 이미지 선택'});await dialog.waitFor();
 assert.equal(await dialog.getByLabel('이미지 검색').evaluate(e=>e===document.activeElement),true);
 await dialog.getByRole('button',{name:'흥부의 다른 모습',exact:true}).click();
 assert.equal(await dialog.locator('.asset-picker-card').count(),9);
 await dialog.getByRole('button',{name:'더 찾기',exact:true}).click();
 await dialog.locator('summary').filter({hasText:/^행동/}).click();
 await dialog.getByRole('group',{name:'행동 조건',exact:true}).getByRole('button',{name:/^일하기/}).click();
 assert.equal(await dialog.locator('.asset-picker-card').count(),1);
 await dialog.locator('.asset-picker-option').click();
 assert.ok(await dialog.locator('.asset-picker-preview').getByText(/일하기/).count());
 await dialog.getByRole('button',{name:'취소',exact:true}).click();
 assert.ok((await opener.textContent()).includes('기본'));
 await page.waitForFunction(()=>document.activeElement===document.querySelector(".scene-essential-assets button"));
 assert.ok(await opener.evaluate(e=>e===document.activeElement));
 await opener.click();await dialog.getByRole('button',{name:'더 찾기',exact:true}).click();
 await dialog.locator('summary').filter({hasText:/^작품/}).click();
 const packs=dialog.getByRole('group',{name:'작품 조건',exact:true});
 await packs.getByRole('button',{name:/^흥부와 놀부/}).click();await packs.getByRole('button',{name:/^선녀와 나무꾼/}).click();
 await dialog.locator('summary').filter({hasText:/^감정·상태/}).click();
 const emotions=dialog.getByRole('group',{name:'감정·상태 조건',exact:true});
 await emotions.getByRole('button',{name:/^걱정/}).click();await emotions.getByRole('button',{name:/^생각/}).click();
 const found=await dialog.locator('.asset-picker-card').count();assert.ok(found>2);
 for(const name of ['종류별','작품별','캐릭터별']) {await dialog.getByRole('button',{name,exact:true}).click();assert.equal(await dialog.getByLabel('현재 찾는 조건').getByRole('button').count(),5);}
 await dialog.getByLabel('이미지 검색').fill('없는그림검색어');await dialog.getByText('찾은 이미지가 없어요.',{exact:true}).waitFor();
 await dialog.getByLabel('현재 찾는 조건').getByRole('button',{name:'모두 지우기',exact:true}).click();
 await dialog.getByRole('button',{name:'소품 둘러보기',exact:true}).click();assert.equal(await dialog.locator('.asset-picker-card').count(),2);
 await dialog.locator('.asset-picker-option').first().click();assert.ok(await dialog.getByRole('button',{name:'이 이미지 사용',exact:true}).isDisabled());
 await dialog.getByRole('button',{name:'소품 둘러보기',exact:true}).click();
 await dialog.getByRole('button',{name:'흥부의 다른 모습',exact:true}).click();
 await dialog.getByLabel('이미지 검색').fill('일하기');
 await dialog.locator('.asset-picker-favorite').click();
 await dialog.getByRole('button',{name:'즐겨찾기',exact:true}).click();assert.equal(await dialog.locator('.asset-picker-card').count(),1);
 await dialog.locator('.asset-picker-option').click();
 await dialog.screenshot({path:`${output}/character-${width}.png`});
 await dialog.getByRole('button',{name:'이 이미지 사용',exact:true}).click();await dialog.waitFor({state:'hidden'});
 assert.ok((await opener.textContent()).includes('일하기'));
 const bg=page.locator('.scene-essential-assets button').nth(2);await bg.click();
 const background=page.getByRole('dialog',{name:'컷 배경 이미지 선택'});
 await background.getByRole('button',{name:'더 찾기',exact:true}).click();
 await background.locator('summary').filter({hasText:/^계절/}).click();
 await background.getByRole('group',{name:'계절 조건',exact:true}).getByRole('button',{name:/^겨울/}).click();
 await background.getByLabel('이미지 검색').fill('집');assert.ok(await background.locator('.asset-picker-card').count()>0);
 await background.screenshot({path:`${output}/background-${width}.png`});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 const visibleButtons=await background.locator('button').evaluateAll(bs=>bs.filter(b=>b.getClientRects().length).map(b=>({text:b.textContent,height:b.getBoundingClientRect().height})));
 assert.ok(visibleButtons.every(b=>b.height>=44),JSON.stringify(visibleButtons.filter(b=>b.height<44)));
 await background.getByRole('button',{name:'이 이미지 사용',exact:true}).focus(); // disabled may not focus, use close for trap.
 await background.getByRole('button',{name:'이미지 선택 닫기',exact:true}).focus();await page.keyboard.press('Shift+Tab');
 assert.ok(await background.evaluate(e=>e.contains(document.activeElement)));
 await page.keyboard.press('Escape');await background.waitFor({state:'hidden'});await page.waitForFunction(()=>document.activeElement===document.querySelectorAll(".scene-essential-assets button")[2]);assert.ok(await bg.evaluate(e=>e===document.activeElement));
 console.log(JSON.stringify({width,found,previewCancel:true,apply:true,facetOrAnd:true,viewPreservesQuery:true,propsReadOnly:true,favorites:true,keyboard:true}));
 await page.close();
}}finally{await browser.close();}
