import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {launchBrowser} from './support/runtime.mjs';
const doc=execFileSync(process.execPath,['--disable-warning=ExperimentalWarning','--experimental-strip-types','--experimental-loader=./tests/node-types-loader.mjs','--input-type=module','-e',`
import {DEFAULT_PROJECT,cloneProject} from './app/story-data.ts';import {createStoryDocument} from './app/story-project-document.ts';
const p=cloneProject(DEFAULT_PROJECT);p.chapters=p.chapters.slice(0,1);const l=p.lines[0];
p.lines=[{...l,id:'short',order:1,type:'dialogue',speaker:'left',speakerName:'토끼',text:'짧은 말이에요.'},{...l,id:'long',order:2,type:'dialogue',speaker:'right',speakerName:'자라',text:'긴 이야기에서도 글을 읽고 다음 컷으로 갈 수 있어요. '.repeat(90)}];
console.log(JSON.stringify(createStoryDocument({project:p,savedAt:'2026-09-10T00:00:00.000Z',appVersion:'qa'})));`],{encoding:'utf8'}).trim();
const browser=await launchBrowser('/tmp/reader-layout-qa');
try {for(const [width,height] of [[1365,900],[390,844]]) {
const page=await browser.newPage({viewport:{width,height},reducedMotion:'reduce'});
await page.addInitScript(doc=>{localStorage.setItem('storygame:draft:v1',doc);localStorage.setItem('storygame:active:v1',doc);},doc);
await page.goto(process.env.QA_URL||'http://localhost:3003');await page.locator('.entry-template-options[open]').waitFor({state:'attached'});
await page.getByRole('button',{name:'나만의 이야기 창작 공작소 열기'}).click();await page.getByRole('button',{name:'이어만들기',exact:true}).click();
await page.getByRole('button',{name:'이 컷 꾸미기',exact:true}).click();
await page.getByRole('group',{name:'함께 말하는 화자',exact:true}).getByRole('checkbox',{name:'자라',exact:true}).check();
await page.getByRole('button',{name:'창작 관리',exact:true}).click();
assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('storygame:projects:v1')).projects[0].draft.project.lines[0].coSpeakerNames),['자라']);
await page.getByRole('button',{name:'읽기',exact:true}).click();await page.getByRole('button',{name:'이야기 펼치기',exact:true}).click();
const transcript=page.locator('.reading-transcript');
await page.waitForFunction(()=>document.querySelector('.reading-transcript')?.getAttribute('data-auto-font-size')==='36');
assert.equal(await transcript.getAttribute('data-auto-font-size'),'36');
const actor=page.locator('.player-shell .story-stage-actor').first();const before=await actor.boundingBox();
const speaker=page.locator('.current-reading .dialogue-speaker');const firstColor=await speaker.evaluate(el=>getComputedStyle(el).color);
await page.getByRole('button',{name:'다음 컷',exact:true}).click();await page.getByText('자라',{exact:true}).waitFor();
await page.waitForFunction(()=>document.querySelector('.reading-transcript')?.getAttribute('data-auto-font-size')==='28');
assert.equal(await transcript.getAttribute('data-auto-font-size'),'28');
assert.notEqual(await speaker.evaluate(el=>getComputedStyle(el).color),firstColor);
const box=await page.locator('.dialogue-box').boundingBox();assert.ok(Math.abs(box.height-height*.35)<2);assert.deepEqual(await actor.boundingBox(),before);
await page.getByRole('button',{name:'글씨 크게',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('.reading-transcript')?.getAttribute('data-font-offset')==='2'&&document.querySelector('.reading-transcript')?.getAttribute('data-auto-font-size')==='30');
assert.deepEqual(await actor.boundingBox(),before);
await page.getByRole('button',{name:'지난 기록',exact:true}).click();const history=page.getByRole('dialog',{name:'지난 기록',exact:true});
assert.equal(await history.locator('.reading-paragraph').count(),2);assert.ok(Math.abs((await history.boundingBox()).width/2+(await history.boundingBox()).x-width/2)<2);
assert.equal(await history.locator('.reading-paragraph').first().evaluate(el=>getComputedStyle(el).fontSize),'34px');
await page.screenshot({path:'/tmp/reader-layout-qa/history-'+width+'.png'});await history.getByRole('button',{name:'닫기',exact:true}).click();
await page.getByRole('button',{name:'이전',exact:true}).click();assert.equal(await speaker.evaluate(el=>getComputedStyle(el).color),firstColor);
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.close();console.log('reader layout '+width+' passed');
}
const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});
const shortDoc=JSON.parse(doc);shortDoc.project.lines[1].text='함께 길을 나섰어요.';
await page.addInitScript(doc=>{if(!localStorage.getItem('storygame:projects:v1')){localStorage.setItem('storygame:draft:v1',doc);localStorage.setItem('storygame:active:v1',doc);}},JSON.stringify(shortDoc));
await page.goto(process.env.QA_URL||'http://localhost:3003');await page.locator('.entry-template-options[open]').waitFor({state:'attached'});
await page.getByRole('button',{name:'나만의 이야기 창작 공작소 열기'}).click();await page.getByRole('button',{name:'이어만들기',exact:true}).click();
await page.getByRole('button',{name:'이 컷 꾸미기',exact:true}).click();
await page.getByRole('group',{name:'함께 말하는 화자',exact:true}).getByRole('checkbox',{name:'자라',exact:true}).check();
await page.getByRole('button',{name:'플레이에 적용',exact:true}).click();
await page.waitForFunction(()=>JSON.parse(localStorage.getItem('storygame:projects:v1')).projects[0].playback.project.lines[0].coSpeakerNames?.includes('자라'));
await page.reload();await page.locator('.creator-shell').waitFor();
await page.getByRole('button',{name:'창작 관리',exact:true}).click();await page.getByRole('button',{name:'읽기',exact:true}).click();await page.getByRole('button',{name:'이야기 펼치기',exact:true}).click();
await page.locator('.current-reading .dialogue-speaker').first().waitFor();
assert.deepEqual(await page.locator('.current-reading .dialogue-speaker').allTextContents(),['토끼','자라']);
await page.getByRole('button',{name:'지난 기록',exact:true}).click();
assert.deepEqual(await page.getByRole('dialog',{name:'지난 기록'}).locator('.dialogue-speaker').allTextContents(),['토끼','자라']);
await page.close();console.log('multi-speaker apply/reconnect/read passed');
} finally {await browser.close();}
