import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const output=process.env.QA_OUTPUT || '/tmp/sticky-memos-qa';await mkdir(output,{recursive:true});
const doc=execFileSync(process.execPath,['--experimental-strip-types','--experimental-loader=./tests/node-types-loader.mjs','--input-type=module','-e',`import {DEFAULT_PROJECT,cloneProject} from './app/story-data.ts';import {createStoryDocument} from './app/story-project-document.ts';const p=cloneProject(DEFAULT_PROJECT);p.chapters=p.chapters.slice(0,1);p.lines=[{...p.lines[0],text:'메모를 참고하며 글을 써요.'},{...p.lines[0],id:'second',order:2,text:'다음 컷'}];p.creativeMemos=[];console.log(JSON.stringify(createStoryDocument({project:p,savedAt:new Date().toISOString(),appVersion:'test'})));`],{encoding:'utf8'}).trim();
const browser=await chromium.launch({channel:'chrome',headless:true});const results=[];
async function resume(page){await page.locator('.entry-template-options[open]').waitFor({state:'attached'});await page.getByRole('button',{name:'나만의 이야기 창작 공작소 열기'}).click();await page.getByRole('tab',{name:/이어만들기/}).click();await page.getByText('이 기기에서 이어만들기 ➔').click();}
try{for(const [width,height] of [[1365,900],[820,1180],[390,844]]){
 console.log('viewport',width);const page=await browser.newPage({viewport:{width,height}});const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto(process.env.QA_URL || 'http://localhost:3002');await page.evaluate(doc=>{localStorage.setItem('storygame:draft:v1',doc);localStorage.setItem('storygame:active:v1',doc)},doc);await page.reload();await resume(page);
 await page.getByRole('button',{name:'컷 꾸미기',exact:true}).first().click();
 await page.getByRole('button',{name:/창작 메모 펼치기/}).click();
 const board=page.getByRole('region',{name:'창작 메모',exact:true});await board.getByRole('button',{name:'+ 메모',exact:true}).click();
 const long='참고할 비밀: 웃으면서 말하기\n'+'긴 생각을 적어 두어요.\n'.repeat(60);
 await board.getByLabel('메모 내용',{exact:true}).fill(long);
 await board.locator('summary').click();await board.getByLabel('제목 (선택)').fill('인물의 비밀');
 const chapterId=JSON.parse(doc).project.chapters[0].id;await board.getByLabel('메모 범위',{exact:true}).selectOption(chapterId);
 await board.locator('summary').click();
 await page.getByLabel('현재 컷 글상자',{exact:true}).fill('웃으면서 대답했다.');
 assert.ok(await board.isVisible());
 await board.getByLabel('보여줄 메모').selectOption('story');assert.equal(await board.getByLabel('메모 내용',{exact:true}).count(),0);
 await board.getByRole('button',{name:'+ 메모',exact:true}).click();await board.getByLabel('메모 내용',{exact:true}).first().fill('작품 전체 참고');
 await board.getByLabel('보여줄 메모').selectOption(chapterId);assert.equal(await board.getByLabel('메모 내용',{exact:true}).inputValue(),long);
 assert.ok(await board.getByLabel('메모 내용',{exact:true}).evaluate(el=>el.scrollHeight>el.clientHeight));
 await page.screenshot({path:`${output}/notes-${width}.png`,fullPage:true});
 await board.getByRole('button',{name:'창작 메모 닫기'}).click();assert.equal(await page.getByLabel('현재 컷 글상자',{exact:true}).inputValue(),'웃으면서 대답했다.');
 await page.getByRole('button',{name:/창작 메모 펼치기/}).click();
 await page.getByRole('button',{name:'다음 컷 →',exact:true}).click();
 await board.getByRole('button',{name:'창작 메모 닫기'}).click();
 assert.equal(await page.getByLabel('현재 컷 글상자',{exact:true}).inputValue(),'다음 컷');
 await page.reload();await resume(page);await page.getByRole('button',{name:/창작 메모 펼치기/}).click();
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('storygame:draft:v1')).project);
 assert.equal(saved.creativeMemos.length,2);assert.equal(saved.creativeMemos[0].fields[0].value,long);assert.equal(saved.creativeMemos[0].linkedChapterId,chapterId);
 assert.equal(saved.lines[0].text,'웃으면서 대답했다.');
 const active=await page.evaluate(()=>JSON.parse(localStorage.getItem('storygame:active:v1')).project);assert.equal(active.creativeMemos.length,0);
 await board.getByRole('button',{name:'창작 메모 닫기'}).click();
 await page.getByRole('button',{name:'메인으로',exact:true}).click();
 await page.locator('.entry-template-options[open]').waitFor({state:'attached'});
 await page.getByRole('button',{name:'나만의 이야기 창작 공작소 열기'}).click();await page.getByRole('tab',{name:/이어만들기/}).click();
 await page.route('https://docs.google.com/spreadsheets/**',route=>route.fulfill({status:500,body:'temporary server failure'}));
 await page.getByLabel('공개 Google 시트',{exact:true}).fill('https://docs.google.com/spreadsheets/d/test_sheet_12345/edit');
 await page.getByRole('button',{name:'시트에서 이어만들기',exact:true}).click();
 await page.getByRole('button',{name:'확인하고 닫기',exact:true}).click();
 const afterFailedImport=await page.evaluate(()=>JSON.parse(localStorage.getItem('storygame:draft:v1')).project);
 assert.deepEqual(afterFailedImport,saved);
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 results.push({width,height,writeBesideMemo:true,scope:true,longScroll:true,reload:true,activeSeparate:true,failedImportPreservesDraft:true,currentCutPreserved:true});await page.close();
}await writeFile(`${output}/results.json`,JSON.stringify(results,null,2));console.log(results);}finally{await browser.close();}
